"""Causal counterfactual augmentation for the retrieval model (the "do-calculus"
track), regenerated for the v2 contrast/SNR observable.

WHAT THE OLD DSCM DID (src/causal/cnn_trnas/*)
    A conditional VAE learned S = g(Z, A, E) + noise, where A = atmospheric
    abundances (the retrieval target) and E = observing/host environment
    (star temperature, distance, star class, surface T/P). Counterfactuals were
    generated by abduction (encode Z | S,A,E), intervention (E → E' by shuffling)
    and prediction (S_cf = S + g(Z,A,E') − g(Z,A,E)), then used to AUGMENT the
    training set with "same atmosphere, different environment" examples so the
    retriever becomes invariant to the host/observing environment (the worst-case
    nuisance the environment probe found was distance).

WHY WE DO NOT RE-USE THAT VAE HERE
    (1) It was trained on the OLD planet-flux cache with a different
    normalisation, and recovered E through a *brittle KDTree match on labels*
    (its own code flags this) because that cache stored no planet IDs.
    (2) A learned decoder is an approximation whose counterfactuals are only as
    good as its reconstructions — and a freshly-trained VAE is a fragile
    dependency to stand a multi-hour retrieval run on.

THE EXACT COUNTERFACTUAL WE USE INSTEAD (module re-pairing)
    INARA's generative process draws the atmospheric composition A from priors
    that are INDEPENDENT of the host star and distance (Zorzan+25, Table 1). The
    structural model therefore FACTORISES:

        contrast C(λ) = albedo(A) · geom       (atmosphere module; F_star cancels)
        SNR(λ)        = α · F_star / noise      (observing-environment module)

    Because the atmosphere module ⟂ the environment module in the data-generating
    process, the EXACT environment counterfactual for a unit is obtained by
    re-pairing: keep planet i's atmosphere (its contrast, hence its label A_i),
    and swap in a different real system j's star brightness F_star_j and noise_j.
    No latent abduction, no learned decoder, no risk of unphysical spectra — the
    counterfactual is built from real observed quantities. This is a strictly
    stronger causal statement than the VAE: it is the true interventional
    distribution do(environment = j), not a model estimate of it.

    Construction (per selected sample i, partner j drawn within the batch):
        F_star_i   = star_planet_i − planet_i          (host star of i)
        albedo_i   = planet_i / F_star_i               (atmosphere+geometry, star-free)
        planet_cf      = albedo_i · F_star_j           (i's atmosphere under star j)
        star_planet_cf = F_star_j + planet_cf
        noise_cf       = noise_j
    One line of algebra shows contrast_cf = planet_cf/star_planet_cf =
    planet_i/star_planet_i EXACTLY — the composition signal (and its label A_i) is
    preserved bit-for-bit, while the SNR channel becomes α·F_star_j/noise_j, i.e.
    environment j. So the model is shown the SAME atmosphere under a DIFFERENT
    observing environment — exactly the invariance the DSCM aimed for.

SAFETY
    * Applied ONLY in the training collate (like the cloud augmentation); the
      frozen val/test observables are never touched → the leakage probe and all
      reported metrics are unaffected, and there is NO test leakage by
      construction.
    * Composition-preserving: labels are never altered, so no label noise.
    * Partner j is drawn within the batch each step, so every epoch sees fresh
      (atmosphere, environment) pairings — augmentation diversity without storing
      a doubled training set in memory.
"""

from __future__ import annotations

import torch

from common.inputs import NoiseCollate
from common.observable import inject_noise, _TINY

CF_PROB = 0.5  # fraction of each batch replaced by an environment counterfactual


class CFNoiseCollate(NoiseCollate):
    """NoiseCollate + per-batch exact environment counterfactuals (the causal
    track). A fraction ``cf_prob`` of each batch has its host star + noise swapped
    for another sample's (composition held fixed), before the usual noise
    injection and exposure-time augmentation.
    """

    def __init__(self, obs_mode, norm, alpha=1.0, base_seed=0, alpha_range=None,
                 cf_prob=CF_PROB):
        super().__init__(obs_mode, norm, alpha, base_seed, alpha_range=alpha_range)
        self.cf_prob = float(cf_prob)

    def __call__(self, batch):
        idxs = [b[0] for b in batch]
        xs = torch.stack([b[1] for b in batch]).clone()   # (B, 2, L)  ch0=star_planet ch1=planet
        ns = torch.stack([b[2] for b in batch]).clone()   # (B, L)
        ys = torch.stack([b[3] for b in batch])           # (B, D)  labels — never modified
        gen = self._gen(idxs)
        B = xs.shape[0]

        sp, pl = xs[:, 0, :], xs[:, 1, :]
        f_star = torch.clamp(sp - pl, min=_TINY)           # host star of each sample
        albedo = pl / f_star                               # atmosphere+geometry (star-free)

        perm = torch.randperm(B, generator=gen)            # counterfactual partner j per sample
        f_star_j = f_star[perm]
        pl_cf = albedo * f_star_j                          # i's atmosphere illuminated by star j
        sp_cf = f_star_j + pl_cf
        ns_cf = ns[perm]

        do_cf = (torch.rand(B, generator=gen) < self.cf_prob).unsqueeze(-1)  # (B,1)
        xs[:, 1, :] = torch.where(do_cf, pl_cf, pl)
        xs[:, 0, :] = torch.where(do_cf, sp_cf, sp)
        ns = torch.where(do_cf, ns_cf, ns)

        a = self._alpha(B, gen)                            # exposure-time augmentation (as usual)
        obs = inject_noise(xs, ns, self.obs_mode, alpha=a, generator=gen)
        return self.norm.encode(obs), ys


class CFInvarianceCollate(NoiseCollate):
    """Counterfactual-INVARIANCE collate — the upgraded do-calculus objective.

    ``CFNoiseCollate`` (above) merely *augments* the batch with counterfactual
    samples: the model is shown more environments and left to infer invariance on
    its own (which, empirically, slightly HURT in-distribution). This collate
    instead returns, for every sample, an **(anchor, counterfactual) pair** that
    share the same atmosphere/label A_i but differ by an EXACT do(environment=j)
    intervention (host star + noise re-paired; composition/contrast preserved
    bit-for-bit). The trainer then adds an explicit penalty forcing the retrieval
    to be INVARIANT across the pair:

        L = task_loss(f(x_i), A_i)  +  λ · ‖ f(x_i) − f(x_i^{do(env=j)}) ‖²   (CLR space)

    Why this is a genuine (not cosmetic) causal contribution, and stronger than
    IRM / domain-generalization: those methods regularise toward invariance across
    *observed, approximate* environments and must estimate the environment split.
    Here the environment intervention is **exact** — it is the true interventional
    distribution do(env=j), obtained in closed form from INARA's factorisation
    (atmosphere ⟂ host/observing environment), with no learned decoder and no
    environment inference. So the invariance target is correct by construction; the
    method directly optimises the environment-invariant retriever the augmentation
    only gestured at. Expected payoff: better host-star/distance robustness and a
    smaller cross-generator / cloud domain-shift gap (to be measured in the
    validation protocol), at the cost of one extra forward pass per step.

    Returns ``(X, y)`` with ``X`` shaped ``(2, B, C, L)``: ``X[0]``=anchor (real
    environment), ``X[1]``=counterfactual (do(env=j)); ``y`` shared. Anchor and
    counterfactual draw INDEPENDENT exposures/noise so the penalty targets the
    environment swap, not a single shared noise realisation. Train-collate only —
    val/test observables are never routed here, so the frozen eval and the leakage
    probe are unaffected and there is no test leakage by construction.
    """

    def __call__(self, batch):
        idxs = [b[0] for b in batch]
        xs = torch.stack([b[1] for b in batch]).clone()   # (B, 2, L)  ch0=star_planet ch1=planet
        ns = torch.stack([b[2] for b in batch]).clone()   # (B, L)
        ys = torch.stack([b[3] for b in batch])           # (B, D)  labels — shared by the pair
        gen = self._gen(idxs)
        B = xs.shape[0]

        sp, pl = xs[:, 0, :], xs[:, 1, :]
        f_star = torch.clamp(sp - pl, min=_TINY)           # host star of each sample
        albedo = pl / f_star                               # atmosphere+geometry (star-free)

        perm = torch.randperm(B, generator=gen)            # counterfactual partner j per sample
        f_star_j = f_star[perm]
        pl_cf = albedo * f_star_j                          # i's atmosphere illuminated by star j
        xs_cf = torch.stack([f_star_j + pl_cf, pl_cf], dim=1)  # (B, 2, L)  do(env = j)
        ns_cf = ns[perm]

        # Independent exposure + noise draws for the two members of the pair.
        a_anchor = self._alpha(B, gen)
        a_cf = self._alpha(B, gen)
        obs_anchor = inject_noise(xs, ns, self.obs_mode, alpha=a_anchor, generator=gen)
        obs_cf = inject_noise(xs_cf, ns_cf, self.obs_mode, alpha=a_cf, generator=gen)
        X = torch.stack([self.norm.encode(obs_anchor),
                         self.norm.encode(obs_cf)], dim=0)  # (2, B, C, L)
        return X, ys
